### PR TITLE
Export 2018 01 11

### PR DESCRIPTION
**Pull request by mTwTm**
Some last minute request to change the wording in on-boarding dialog.

### CODE REVIEW

**Comment by rodin** [comment]
Hi, this is Romi, one of Indonesian translators. 

Just one question before merging: what's the difference between "tracking ads" and "trackers"? The indonesian translation will surely looks weird since "iklan pelacak dan pelacak" doesn't seem logical and on the same "level" - well, why state specific "category": tracking ads, if you already state the broader one: tracker?

**Comment by mTwTm** [comment]
I'll ask our PM Joe who requested this change to answer this question.

**Comment by mTwTm** [comment]
Thanks for asking, Joe has responded but he'll need to further discuss with the team tomorrow. @Delphine let's not merge this before we reach a conclusion.

**Comment by joechengla** [comment]
let's remove "and trackers". so it will be just "tracking ads" (without "and trackers").
Does it work better now?

**Comment by mTwTm** [comment]
I'll update the pr accordingly and reopen it if Romi considers it fine.

**Comment by rodin** [comment]
@joechengla "tracking ads" only will be fine.

**Comment by mTwTm** [comment]
Great! 👍 I'll go for a new pull request after I cleared my backlog.

**Comment by mTwTm** [comment]
I'll send it next week since we seems to got some more new strings.

**Pull request closed without merging**
